[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
  headers = { Access-Control-Allow-Origin = "*" }

[[redirects]]
  from = "/*"
  status = 200
  to = "/index.html"
  headers = { Access-Control-Allow-Origin = "*" }

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
